### PR TITLE
Tried to add Phase 4

### PR DESCRIPTION
**Pull request by BeeFriedman**
Hi, Don't know if you want other people to help out. Tried to add Phase 4.

### CODE REVIEW

**Comment by chrismccolgan** [comment]
Hey I just tested your code out, and I think it's really cool how you stored the user guesses like that! Great job! Please feel free to play around with any of my code. :)

**Comment by BeeFriedman** [comment]
Thanks! i am still new to all of this. Are you going to merge it to you master branch?

**Comment by chrismccolgan** [comment]
I'm new too! You're really talented! I just realized I had to do phase 4 in a different way. When you select the "cheater" difficulty it gives you 10000 guesses, so it was writing 10000 0's to the console lol.

**Comment by BeeFriedman** [comment]
LOL! didn't think of that. Good thing you noticed it.

**Pull request merged**
